# Add PID gains for wheel joints
/gazebo_ros_control/pid_gains/front_left_wheel:
  p: 10.0
  i: 0.01
  d: 1.0
/gazebo_ros_control/pid_gains/front_right_wheel:
  p: 10.0
  i: 0.01
  d: 1.0
/gazebo_ros_control/pid_gains/rear_left_wheel:
  p: 10.0
  i: 0.01
  d: 1.0
/gazebo_ros_control/pid_gains/rear_right_wheel:
  p: 10.0
  i: 0.01
  d: 1.0
